[package]
name = "glicko2"
version = "0.0.0"
authors = ["Christopher Sardegna <gpg@reagentx.net>"]
edition = "2021"

[profile.release]
# Remove symbols from release
strip = true
# Perform Link Time Optimization
lto = true
